### ISSUE TITLE
ValueError: Input X contains infinity or a value too large for dtype('float64').

### ISSUE THREAD

**Issue by hdante** [LSSTDESC/rail_gpz_v1#20]
Hello, everyone, this issue seems to be a variant of issue #17, where magnitude values are infinite. Is it possible to handle this case when sanitizing the values ? Example input file attached. Thanks,

[objectTable_tract_2906_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_2_20220308T164354Z-part9.hdf5.gz](https://github.com/user-attachments/files/16592548/objectTable_tract_2906_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_2_20220308T164354Z-part9.hdf5.gz)

    (base) [henrique.almeida@loginapl01 testgpz]$ rail-estimate -a gpz /lustre/t1/cl/lsst/dp0.2/secondary/catalogs/skinny/objectTable_tract_2906_DC2_2_2i_runs_DP0_2_v23_0_1_PREOPS-905_step3_2_20220308T164354Z-part9.hdf5 output1.hdf5
    Estimator algorithm: gpz
    Estimator calibration file: /lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/share/rail_scripts/estimator_gpz.pkl
    Bins: 301
    HDF5 group name: ""
    Column template for magnitude data: "mag_{band}"
    Column template for error data: "magerr_{band}"
    Extra parameter file: "None"
    Starting setup.
    Loading all program modules...
    Configuring estimator...
    Loading input file...
    Setup done.
    Starting estimate.
    Inserting handle into data store.  model: /lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/share/rail_scripts/estimator_gpz.pkl, estimate
    Process 0 running estimator on chunk 0 - 10000
    Process 0 estimating GPz PZ PDF for rows 0 - 10,000
    Traceback (most recent call last):
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-estimate", line 248, in <module>
        main()
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-estimate", line 244, in main
        estimate(cfg, ctx)
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/slurm-home/bin/rail-estimate", line 236, in estimate
        ctx.estimator.estimate(ctx.input)
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/estimator.py", line 99, in estimate
        self.run()
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/estimator.py", line 112, in run
        self._process_chunk(s, e, test_data, first)
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/algos/gpz.py", line 163, in _process_chunk
        mu, totalV, modelV, noiseV, _ = self.model.predict(test_array)
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/rail/estimation/algos/_gpz_util.py", line 234, in predict
        Xt = self.pca.transform(X)
             ^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/sklearn/utils/_set_output.py", line 313, in wrapped
        data_to_wrap = f(self, X, *args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/sklearn/decomposition/_base.py", line 143, in transform
        X = self._validate_data(
            ^^^^^^^^^^^^^^^^^^^^
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/sklearn/base.py", line 633, in _validate_data
        out = check_array(X, input_name="X", **check_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 1064, in check_array
        _assert_all_finite(
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 123, in _assert_all_finite
        _assert_all_finite_element_wise(
      File "/lustre/t1/cl/lsst/tmp/henrique.almeida/miniconda3/lib/python3.11/site-packages/sklearn/utils/validation.py", line 172, in _assert_all_finite_element_wise
        raise ValueError(msg_err)
    ValueError: Input X contains infinity or a value too large for dtype('float64').

- [x] I have described the situation in which the bug arose, including what code was executed, information about my environment, and any applicable data others will need to reproduce the problem.
- [x] I have included available evidence of the unexpected behavior (including error messages, screenshots, and/or plots) as well as a descriprion of what I expected instead.
- [x] If I have a solution in mind, I have provided an explanation and/or pseudocode and/or task list.

**Comment by sschmidt23** [comment]
We did discuss a standalone data sanitization stage for RAIL at the RAIL workshop, but I don't remember what our conclusion was as to whether we would add one or not.  It's something to discuss at the next RAIL tag-up once we resume those in September.

**Comment by hdante** [comment]
Sam, ok. Does it make sense to add it to GPZ code meanwhile ?

**Comment by sschmidt23** [comment]
Yes, I'll just change the `np.isnan` to `~np.isfinite` in the existing check, which should catch the inf values as well as the nans.  I'll create a quick PR to do this now.

**Comment by sschmidt23** [comment]
@hdante I just merged in a PR that I think should address this, so I'm closing the issue.  I'll roll a new release to PyPI in a minute, if you have any further issues create a new issue here.

**Comment by hdante** [comment]
Hello, Sam, ok, I'll test it, thank you.
